// Generated by x9-assembler
// parameters used in the LUT
package LUT_def;
    // LUT index
    // Generated
    typedef enum {
        LUT_LW = 0,
        LUT_SW = 1,
        LUT_BNE = 2,
        LUT_BEQ = 3,
        LUT_BLTS = 4,
        LUT_BLT = 5
    } LUT_TYPE;

    // LUT[opcode][imm] => value
    const logic[7:0] kLookupTable[2:0][4:0];  // = '{'{}}

endpackage
