// Generated by x9-assembler
// parameters used in the LUT
package LUT_def;
    // LUT index
    const logic [2:0] kLutNone = 3'b000;
    const logic [2:0] kLutBeq  = 3'b001;
    const logic [2:0] kLutBne  = 3'b010;
    const logic [2:0] kLutBlt  = 3'b011;
    const logic [2:0] kLutBgt  = 3'b100;
    const logic [2:0] kLutLw   = 3'b101;
    const logic [2:0] kLutSw   = 3'b110;

endpackage
