// Generated by x9-assembler
// parameters used in the LUT
package LUT_def;
    // LUT index
    // Generated
    typedef enum logic[2:0] {
        LUT_LW = 0,
        LUT_SW = 0,
        LUT_BNE = 0,
        LUT_BEQ = 0,
        LUT_BLTS = 0,
        LUT_BLT = 0,
    } LUT_TYPE;

    // LUT[opcode][imm] => value
    const logic[7:0] kLookupTable[2:0][4:0];  // = '{'{}}

endpackage
